input {
  gelf {
    port => 5000
  }
}

filter {
  if ![@timestamp] {
    mutate {
      add_field => { "[@timestamp]" => "%{+YYYY-MM-dd'T'HH:mm:ss.SSSZ}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "quarkus-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
